apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      component: nginx
  template:
    metadata:
      labels:
        component: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          imagePullPolicy: Always
          command: ["nginx"]
          args: ["-g", "daemon off;"]
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
            - name: labelstudio-data-vol
              mountPath: /label-studio/data
            - name: labelstudio-static-vol
              mountPath: /label-studio/label_studio
            # - name: nginx-dir
            #   mountPath: /etc/nginx/conf.d/
            - name: nginx-empty
              mountPath: /var/cache/nginx/client_temp
            - name: nginx-run
              mountPath: /var/run/           
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
            items:
              - key: "default.conf"
                path: "default.conf"
        - name: labelstudio-data-vol
          persistentVolumeClaim:
            claimName: labelstudio-data-pvc
        - name: labelstudio-static-vol
          emptyDir: {}
        # - name: nginx-dir
        #   emptyDir: { }
        - name: nginx-empty
          emptyDir: { }
        - name: nginx-run
          emptyDir: { }